# Generated by Django 3.0.6 on 2020-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=30)),
                ('variants', models.CharField(max_length=40)),
                ('bhp', models.CharField(max_length=30)),
                ('cc', models.CharField(max_length=30)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=13)),
                ('fuel', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=13)),
                ('price', models.CharField(max_length=15)),
                ('photo1', models.FileField(upload_to='')),
                ('photo2', models.FileField(upload_to='')),
                ('photo3', models.FileField(upload_to='')),
                ('photo4', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('contact_time', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('house_name', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('distric', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('booked_car', models.CharField(default='not booked', max_length=20)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('normal', 'normal')], default='normal', max_length=10)),
                ('approval', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Testdrive',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
