# Generated by Django 3.0.6 on 2020-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='deletion',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='deletion',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
        migrations.AddField(
            model_name='register',
            name='deletion',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='deletion',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
    ]
